### ISSUE TITLE
Como usuário preciso conseguir logar no sistema com segurança

### ISSUE THREAD

**Issue by VianaGu** [VianaGu/ConstruMath#10]
[Diagrama de sequência](https://github.com/VianaGu/ConstruMath/blob/main/Diagramas/Corrigido%20-%20Diagrama%20de%20Sequencia%20-%20Login.png)

- [x] Fazer Login
Com:
- [x] Conexão com banco de dados
- [x] Senha
- [x] Usuário

Critério de aceite:
- Logar apenas com usuário e senha corretos.
- O usuário tem que ser idêntico com cadastro
- Caso um dos dois estiver errado, dar o aviso "login ou senha inválido, tente novamente".

**Comment by VianaGu** [comment]
-[] Mudar fundo 
-[] Mudar cores

**Comment by VianaGu** [comment]
- [ ] Mudar cores
- [ ] Mudar Imagem de fundo

**Comment by VianaGu** [comment]
[Diagrama de exemplo](https://github.com/VianaGu/ConstruMath/blob/main/Diagramas/Corrigido%20-%20Diagrama%20de%20Sequencia%20-%20Login.png)

**Comment by VianaGu** [comment]
Fiz o arquivo que faz conexão com o banco de dados, você encontra [aqui](https://github.com/VianaGu/ConstruMath/blob/main/paginas/conexao.php)

**Comment by davifma** [comment]
Se já fez a conexão a feature está em andamento, fazendo.

**Comment by davifma** [comment]
Preciso de autorização como administrador desse projeto e repositório.

**Comment by VianaGu** [comment]
[> Preciso de autorização como administrador desse projeto e repositório.](https://github.com/VianaGu/ConstruMath/invitations)

**Comment by davifma** [comment]
Temos duas tarefas iguais?

**Comment by VianaGu** [comment]
> Temos duas tarefas iguais?

São bem parecidas mesmo, mas são duas telas diferentes, por isso resolvemos colocar em duas tarefas

**Comment by VianaGu** [comment]
Página de login concluida, você pode encontrá-la [aqui](https://github.com/VianaGu/ConstruMath/blob/main/paginas/login.php)
