### ISSUE TITLE
Como desenvolvedor preciso de uma base de dados para criar um banco de dados

### ISSUE THREAD

**Issue by VianaGu** [VianaGu/ConstruMath#12]
- [x] Pesquisa de materiais 
- [x] Pesquisa do dimensões dos produtos

Critérios de aceite:
Ter uma tabela com uma grande quantidade de dados sobre os materiais

**Comment by F4bricioGit** [comment]
Tabela Criada e pode sem encontrada [aqui](https://github.com/VianaGu/ConstruMath/blob/main/miscel%C3%A2nea/Lista%20de%20estoque%20com%20destaques1.xlsx)
