### ISSUE TITLE
Como usuário gostaria que pudesse fazer os cálculos de quanto de material devo utilizar em minha obra

### ISSUE THREAD

**Issue by VianaGu** [VianaGu/ConstruMath#13]
Livro fornecido pela prof° Larissa San Martins (curso de arquitetura e urbanismo - Ceunsp)
[Material de base](https://github.com/VianaGu/ConstruMath/blob/main/materiais_contrucao.pdf)
[Diagrama de Classe](https://github.com/VianaGu/ConstruMath/tree/main/paginas/calculadora/Calculadora.drawio.pdf)
- [x] Pesquisar sobre traço de cimento 
- [x] Pesquisar media de kg dos materiais 
- [x] Layout da calculadora 
- [x] Funções dos botões 
- [x] calcular brita em metro cúbicos
- [x] calcular peso de pedregulho
- [x] calcular areia em metro cúbicos
- [x] calcular quantidade de cimento
- [x] calcular quantidade de agua para x concreto
- [x] calcular quantidade de materiais necessários

Critério de aceite:
- Conseguir realizar todos os cálculos de quantidades de materiais para auxiliar no planejamento da construção

**Comment by VianaGu** [comment]
@DeividPRomao @rodrigokenzo04 @HugoRochaaa  Fizeram as páginas de calculo

**Comment by davifma** [comment]
Se está completa onde está a documentação?

**Comment by DeividPRomao** [comment]
O Diagrama de Classe da Calculadora foi adicionada no comentário da Issue.
Ou nesse [caminho](https://github.com/VianaGu/ConstruMath/tree/main/paginas/calculadora/Calculadora.drawio.pdf)

**Comment by davifma** [comment]
Cadê o diagrama?

**Comment by davifma** [comment]
O ideal é que o diagrama de classes seja de todo o sistema.
