### ISSUE TITLE
Como usuário preciso conseguir me cadastrar com segurança

### ISSUE THREAD

**Issue by VianaGu** [VianaGu/ConstruMath#14]
[Diagrama de sequência](https://github.com/VianaGu/ConstruMath/blob/main/Diagramas/Corrigido%20-%20Diagrama%20de%20Sequ%C3%AAncia%20Cadastro.png)

- [x] Fazer cadastro
Com:
- [x] E-mail
- [x] Usuário
- [x] Senha
- [x] Com conexão em um banco de dados

Critério de aceite:
 - Aceitar apenas e-mails válidos (exemplo@exemplo.com)
- Não pode haver duplicidade no banco de dados

**Comment by VianaGu** [comment]
Fiz o arquivo que faz conexão com o banco de dados, você encontra [aqui](https://github.com/VianaGu/ConstruMath/blob/main/paginas/conexao.php)

**Comment by davifma** [comment]
Acho que eu entendi, o mesmo arquivo de conexão será usado em vários locais. Importante deixar isso claro na comunicação.

**Comment by VianaGu** [comment]
Isso, Todas as interações com o banco de dados deverá passar por esse arquivo

**Comment by davifma** [comment]
Se o item não acabou não deveria estar no feito

**Comment by VianaGu** [comment]
Você pode encontra a tela de cadastro [aqui](https://github.com/VianaGu/ConstruMath/blob/main/paginas/cadastro.php)
