### ISSUE TITLE
Como desenvolvedor preciso que código esteja documentado para melhor compreensão

### ISSUE THREAD

**Issue by DeividPRomao** [VianaGu/ConstruMath#16]
- [x] Documentação do código inteiro realizada:

- [x] Tela de "Calculadora".
- [x] Tela de "Materiais".
- [x] Tela de "O que construir".
- [x] Tela de "Login".
- [x] Recuperação de senha.
- [x] Tela de "Cadastro de usuário".
- [x] Verificação de usuário.
- [x] Navbar.
- [x] Layout/Formatação em CSS.

Critério de aceite:
- Funções e varáveis documentadas.
- Ter uma documentação de forma clara e objetiva.

**Comment by davifma** [comment]
Onde eu testo essas funcionalidades?
