### ISSUE TITLE
Como usuário preciso que calcule a quantidade de material baseado na dimensões das paredes e piso 

### ISSUE THREAD

**Issue by VianaGu** [VianaGu/ConstruMath#4]
[Diagrama de exeplo](https://github.com/VianaGu/ConstruMath/blob/main/Diagramas/Corrigido%20-%20Diagrama%20de%20Sequ%C3%AAncia%20O%20Que%20Quer%20Construir.png)
- [x] Layout da página 
- [x] Funções de seleção ao calculo de M²(altura * largura) e M³ (largura * comprimento * espessura) 
- [x] Funções de cálculo baseado na seleção anterior 
- [x] Criar botão para mostrar medidas quando clicado
- [x] Fazer pesquisa de média de materiais utilizados para dar uma base de materiais  em determinada construção 

critérios de aceite:
- Consiga digitar qual tipo (parede e piso)
E assim liberar os campos adequados
(Altura, largura e quantidade de portas para parede ou largura, comprimento e espessura para piso)

- Consiga digitar as medidas

- Efetuar o calculo conforme desmontrado nessa <a href="https://github.com/VianaGu/ConstruMath/blob/main/Planilha%20base.xlsx" download="https://github.com/VianaGu/ConstruMath/blob/main/Planilha%20base.xlsx">tabela</a>  de excel

**Comment by VianaGu** [comment]
Layout da página desenvolvido por @GabrielCaleffo e eu, você pode encontrar [aqui](https://github.com/VianaGu/ConstruMath/blob/main/Prints%20Do%20Prot%C3%B3tipo/O%20que%20construir.png)

**Comment by davifma** [comment]
Onde estão os diagramas de Classe e MER?

**Comment by VianaGu** [comment]
Adicionei uma planilha base para teste futuros dessas página

**Comment by VianaGu** [comment]
@GabrielCaleffo Fez os diagramas de classe e MER eu apenas fiz o commit pois ele não conseguiu fazer da casa dele.
Você encontra essa tabela [aqui](https://github.com/VianaGu/ConstruMath/blob/main/Diagramas/Diagrama%20de%20Classe%20e%20MER.xlsx)

**Comment by VianaGu** [comment]
A página do que construir falta apenas as quantidades de materiais

**Comment by davifma** [comment]
[Referente ao Diagrama de Classes](https://github.com/VianaGu/ConstruMath/issues/4#issuecomment-2362319253)
Qual a relação entre as classes?

[Referente ao MER](https://github.com/VianaGu/ConstruMath/issues/4#issuecomment-2362319253)
Temos duas tabelas com o mesmo nome? Ou é a mesma tabela que se relaciona com as outras duas?

**Comment by VianaGu** [comment]
Diagrama de classe [corrigido](https://github.com/VianaGu/ConstruMath/blob/main/Diagramas/Diagrama%20de%20Classe-oqconstruir.drawio.svg)

**Comment by davifma** [comment]
Na Classe oQueConstuir os métodos estão parecendo definições de interface gráfica, o nome da classe também está estranho.

**Comment by VianaGu** [comment]
Diagrama refeito e de forma geral do projeto que pode ser encontrado [aqui](https://github.com/VianaGu/ConstruMath/blob/main/Diagramas/ClassesTodoOSistema.drawio.svg)
e utilizamos a base de quantidade de material nesse [livro](https://github.com/VianaGu/ConstruMath/blob/main/miscel%C3%A2nea/materiais_contrucao.pdf)
